/*
* There are several hardcoded urls that need to be chan
*/
public class Config {

//    public static final String URL_SFDC = 'https://cs1.salesforce.com/';
//   public static final String URL_FORMVIEW = 'https://c.cs1.visual.force.com/apex/SECFormStartPage';

    public static final String URL_SFDC = 'https://na1.salesforce.com/';
    public static final String URL_FORMVIEW = 'https://c.na1.visual.force.com/apex/SECFormStartPage';
    
}