@isTest
private class Test_TempTests {
/*
    static testMethod void myUnitTest() {
        
        SEC_Forms_Question__c question = [select Id, Data_Type__c, Pre_Population__c, QID__c from SEC_Forms_Question__c where Id = 'a09S00000029ps4' limit 1];
        //question.Data_Type__c = 'Short Text';
        //question.QID__c = null;
        //update question;
        
        question.Data_Type__c = 'Comments';
        question.QID__c = 'TEST_QID_3';
        update question;
    }
*/
}